/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smarttermo;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Turma A
 */
public class SmartTermo extends javax.swing.JFrame {

    /**
     * Creates new form termostato
     */
    public SmartTermo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempDesejada = new javax.swing.JLabel();
        PlusTemp = new javax.swing.JButton();
        MinusTemp = new javax.swing.JButton();
        Unidade = new javax.swing.JButton();
        tempActual = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        setTo = new javax.swing.JLabel();
        setToUni = new javax.swing.JLabel();
        tempActualNum = new javax.swing.JLabel();
        tempIdealUni = new javax.swing.JLabel();
        HeatToggle = new javax.swing.JToggleButton();
        plusHumidity = new javax.swing.JButton();
        minusHumidity = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        humiSetTo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tempDesejada.setText("Temp Desejada :");

        PlusTemp.setText("PlusTemp");
        PlusTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusTempActionPerformed(evt);
            }
        });

        MinusTemp.setText("MinusTemp");
        MinusTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusTempActionPerformed(evt);
            }
        });

        Unidade.setText("Celsius");
        Unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnidadeActionPerformed(evt);
            }
        });

        tempActual.setText("Temp Ideal:");

        jLabel2.setText("Celsius/Fahrenheit");

        setTo.setText("22");

        setToUni.setText("Celsius");

        tempActualNum.setText("25");

        tempIdealUni.setText("Celsius");

        HeatToggle.setText("Heater");
        HeatToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeatToggleActionPerformed(evt);
            }
        });

        plusHumidity.setText("plusHumidity");
        plusHumidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusHumidityActionPerformed(evt);
            }
        });

        minusHumidity.setText("minusHumidity");
        minusHumidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusHumidityActionPerformed(evt);
            }
        });

        jLabel1.setText("Humidade Desejada ");

        humiSetTo.setText("40");

        jLabel4.setText("%");

        jLabel3.setText("Data Actual:");

        jLabel5.setText("Humidade Ideal:");

        jLabel6.setText("30");

        jLabel7.setText("%");

        jLabel8.setText("qualquercoisa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(plusHumidity)
                                            .addComponent(minusHumidity)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(humiSetTo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addGap(191, 191, 191)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tempActualNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempIdealUni))
                                    .addComponent(tempActual)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(Unidade)
                            .addGap(11, 11, 11))
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MinusTemp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(setTo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(setToUni))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PlusTemp)
                                        .addComponent(tempDesejada))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(HeatToggle)
                                .addGap(11, 11, 11)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Unidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlusTemp)
                            .addComponent(plusHumidity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tempDesejada)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(setTo)
                                    .addComponent(setToUni)
                                    .addComponent(humiSetTo)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tempActual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tempActualNum)
                                    .addComponent(tempIdealUni))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MinusTemp)
                            .addComponent(minusHumidity)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(HeatToggle))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnidadeActionPerformed
        if (setToUni.getText() == "Celsius") {
            double newtemp = (Double.parseDouble(setTo.getText()) * 9 / 5) + 32;
            setTo.setText(Double.toString(Math.ceil(newtemp * 10) / 10));
            setToUni.setText("Fahrenheit");

            newtemp = (Double.parseDouble(tempActualNum.getText()) * 9 / 5) + 32;
            tempActualNum.setText(Double.toString(Math.ceil(newtemp * 10) / 10));
            tempIdealUni.setText("Fahrenheit");
        } else if (setToUni.getText() == "Fahrenheit") {
            double newtemp = (Double.parseDouble(setTo.getText()) - 32) * 5 / 9;
            setTo.setText(Double.toString(Math.ceil(newtemp * 10) / 10));
            setToUni.setText("Celsius");

            newtemp = (Double.parseDouble(tempActualNum.getText()) - 32) * 5 / 9;
            tempActualNum.setText(Double.toString(Math.ceil(newtemp * 10) / 10));
            tempIdealUni.setText("Celsius");
        }
    }//GEN-LAST:event_UnidadeActionPerformed

    private void PlusTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusTempActionPerformed
        double plustemp = Double.parseDouble(setTo.getText());
        plustemp = plustemp + 0.5;
        setTo.setText(Double.toString(Math.ceil(plustemp * 10) / 10));
    }//GEN-LAST:event_PlusTempActionPerformed

    private void MinusTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusTempActionPerformed
        double plustemp = Double.parseDouble(setTo.getText());
        plustemp = plustemp - 0.5;
        setTo.setText(Double.toString(Math.ceil(plustemp * 10) / 10));
    }//GEN-LAST:event_MinusTempActionPerformed

    private void HeatToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeatToggleActionPerformed
        if (Double.parseDouble(setTo.getText()) > Double.parseDouble(tempActualNum.getText())) {
            while (Double.parseDouble(setTo.getText()) > Double.parseDouble(tempActualNum.getText())) {
                double heaterOn = Double.parseDouble(tempActualNum.getText());
                heaterOn = heaterOn + 0.5;
                tempActualNum.setText(Double.toString(Math.ceil(heaterOn * 10) / 10));  
            }
        }
    }//GEN-LAST:event_HeatToggleActionPerformed

    private void plusHumidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusHumidityActionPerformed
       int newHumi = Integer.parseInt(humiSetTo.getText());
       newHumi+=5;
       humiSetTo.setText(Integer.toString(newHumi));
    }//GEN-LAST:event_plusHumidityActionPerformed

    private void minusHumidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusHumidityActionPerformed
        int newHumi = Integer.parseInt(humiSetTo.getText());
       newHumi-=5;
       humiSetTo.setText(Integer.toString(newHumi));
    }//GEN-LAST:event_minusHumidityActionPerformed

    public JLabel getTemp() {
        return setTo;
    }

    public void setTemp(JLabel temp) {
        this.setTo = temp;
    }

    public JButton getPlusTemp() {
        return PlusTemp;
    }

    public JButton getMinusTemp() {
        return MinusTemp;
    }

    public JButton getUnidade() {
        return Unidade;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartTermo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton HeatToggle;
    private javax.swing.JButton MinusTemp;
    private javax.swing.JButton PlusTemp;
    private javax.swing.JButton Unidade;
    private javax.swing.JLabel humiSetTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton minusHumidity;
    private javax.swing.JButton plusHumidity;
    private javax.swing.JLabel setTo;
    private javax.swing.JLabel setToUni;
    private javax.swing.JLabel tempActual;
    private javax.swing.JLabel tempActualNum;
    private javax.swing.JLabel tempDesejada;
    private javax.swing.JLabel tempIdealUni;
    // End of variables declaration//GEN-END:variables
}
